import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        String mobileInputMsg = "This is your message";
        Mobile m = new Mobile();
        m.call(mobileInputMsg);
        IPhone iPhone = new IPhone();
        iPhone.call(mobileInputMsg);
        Andriod andriod = new Andriod();
        andriod.call(mobileInputMsg);
    }
}
