import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        List<Mobile> mobiles = new ArrayList<Mobile>();
        mobiles.add(new IPhone());
        mobiles.add(new Andriod());

        for(Mobile mobile: mobiles) {
            Person person = new Person("Amiao", mobile);
            person.call("I'm " + person.getName());
        }

        IPhoneRobot robot = new IPhoneRobot();
        robot.call(new IPhone(),"This is robot message");

        Person person = new Person("Amiao", new Andriod());
        person.setMobile(new IPhone());
        person.call("This is changed phone msg");
    }
}
