/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.sun.org.apache.xpath.internal.operations.And;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    private String mobileInputMsg = "This is your message";

    @Test
    public void testMobileCall() {
        Mobile mobile = new Mobile();
        assertEquals("Message : This is your message", mobile.call(mobileInputMsg));
    }

    @Test
    public void testIPhoneCall() {
        IPhone iPhone = new IPhone();
        assertEquals("<iPhone>Message : This is your message", iPhone.call(mobileInputMsg));
    }

    @Test
    public void testAndroidCall() {
        Andriod andriod = new Andriod();
        assertEquals("<Android>Message : This is your message", andriod.call(mobileInputMsg));
    }
}
