/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.sun.org.apache.xpath.internal.operations.And;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    private String mobileInputMsg = "This is your message";

    @Test
    public void testPersonCallByIPhone() {
        Person person = new Person("Amiao", new IPhone());
        assertEquals("<iPhone>Message : This is your message", person.call(mobileInputMsg));
    }

    @Test
    public void testPersonCallByAndroid() {
        Person person = new Person("Amiao", new Andriod());
        assertEquals("<Andriod> Message cannot be sent", person.call(mobileInputMsg));
    }

    @Test
    public void testIPhoneRobotCalls() {
        IPhoneRobot robot = new IPhoneRobot();
        assertEquals("<iPhone>Message : This is robot message", robot.call(new IPhone(),"This is robot message"));
    }

    @Test
    public void testChangedPhoneForPerson() {
        Person person = new Person("Amiao", new Andriod());
        person.setMobile(new IPhone());
        assertEquals("<iPhone>Message : This is changed phone msg", person.call("This is changed phone msg"));
    }
}
